# Generated by Django 5.0.1 on 2024-01-21 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewHandout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('handout', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='handout.handout')),
            ],
        ),
    ]
